tests/bootstrap.php
If GLPI configuration fails, unit tests might silently fail. This commit checks config_db.php actually exists before running them
=> [WIP] tests: checks GLPI is configured

front/config.form.php, inc/agent.class.php, inc/config.class.php, inc/menu.class.php, tpl/config-debug.html, tpl/config-messagequeue.html, tpl/config.html
Divide the configuration of the plugin into several subpages
This prepares the UI to provide more settings in an organized UI. We can consider adding an assistant to help the admin to setup the whole solution with snippets of configuration files.
closes #152
=> Split configuration into several tabs

inc/mqtthandler.class.php
A datetime received by the agent is expected to be in UTC timezone. We need to shift it to the server's timezone before saving it.
=> shift received datetime to server's timezone

inc/package.class.php
If an update occurs on a package but the APK remains  the same, a analyze  request is sent to Orion. It is useless. Let's scan only on an update of the APK file.
=> Scan requests when the apk does not change

install/upgrade/update_to_dev.php
Prevent warnings when adding policy categories when upgrading several times.
Remove a right which does not exists and produces a malforled, useless right. Also produced a warning if we repeat upgrade process.
=> avoid some warnings

install/installer.class.php
An URL in the HTML version of the invitation email is displayed without its anchor.
=> HTML version of template is missing an anchor

tests/suite-integration/PluginFlyvemdmAgent.php
A unit test fails. Here is the fix. This is only a misordered vars in the list.
=> Fix misordered list

inc/fleet.class.php, tests/suite-integration/PluginFlyvemdmAgent.php, tests/suite-unit/PluginFlyvemdmFleet.php
A default policy has nothing to do with policies. Hide the tab
=> Hide policies tab for not managed fleets

inc/config.class.php, inc/notificationtargetinvitation.class.php, install/installer.class.php, install/upgrade/update_to_dev.php, setup.php, tpl/config.html
Hi
This is for now a draft. I need to validate it.
This PR introduces a new setting to customize the base URL of a deeplink used in invitations
On save, a trailing slash is added if missing.
=> [WIP] Deeplink is customizable

tests/bootstrap.php, tests/suite-integration/PluginFlyvemdmAgent.php
=> Make unit tests able to send backtrace on fatal errors

inc/invitation.class.php, inc/notificationtargetinvitation.class.php
The QR code was not valid, missed the prefix of the URL found in the configuration of  the plugin.
Factorized the code.
=> Incomplete URL in qr code

inc/invitation.class.php, inc/notificationtargetinvitation.class.php, tests/suite-integration/PluginFlyvemdmInvitation.php, tests/suite-unit/PluginFlyvemdmInvitation.php, tests/suite-unit/PluginFlyvemdmPolicyDeployapplication.php
It seems the QR code must be linked to the invitation with the relation table glpi_documents_items.
The PR needs cleanup : the column documents_id in the invitation is now obsolete. Needs to migrate the existing rows to the new way and probably update the hooks.
=> Qr code in email was missing

inc/agent.class.php, tests/suite-install/Config.php, tests/suite-integration/PluginFlyvemdmAgent.php
When a device enrolls an agent is created in the DB with an associated user.
This user does not has the expected profile :-1: 
=> Fix wrong user profile in enrollment

tpl/config-wizard.html.twig
Add certificate information on TLS Step and suggest the use of OpenSSL in Wizard
Also in the [message queue section](http://flyvemdm-doc.readthedocs.io/en/latest/config/message-queue.html)
Closes #N/A
=> Certificate information on TLS step

inc/agent.class.php, inc/fleet.class.php, inc/notifiableinterface.class.php, inc/policybase.class.php, inc/policydeployapplication.class.php, inc/policydeployfile.class.php, inc/policyinterface.class.php, inc/policyremoveapplication.class.php, inc/task.class.php, install/installer.class.php, tests/suite-unit/PluginFlyvemdmPolicyBase.php, tests/suite-unit/PluginFlyvemdmPolicyDeployapplication.php, tests/suite-unit/PluginFlyvemdmPolicyDeployfile.php, tests/suite-unit/PluginFlyvemdmPolicyRemoveapplication.php
I recommend reviewing this PR commit by commit
- drop useless code in remove app policy
- in consequence, rename appy / unapply into pre_apply / pre_unapply
- harmonize arguments of methods for policies
- append **Interface** at the end of PluginFlyvemdmNotifiable to harmonize with PluginFlyvemdmPolicyIntrerface
=> Code cleanup

install/installer.class.php, tests/suite-install/Config.php
Reset the is_recursive flag to 0 when installing a default fleet in root entity
=> Fleet in  the root entity should not be recursive

.travis.yml
Maybe we should finish the documentation generation script by instructions to go back to the original branch.
=> Invert build after_success sequence

inc/agent.class.php, tests/suite-integration/PluginFlyvemdmAgent.php
also improve / fix unit tests for enrollment
the purpose if the XML validation is to early detect import failure in Fusion Inventory
and avoid the invitation token to be consumed
=> Validate inventory XML

composer.json, front/invitation.form.php, hook.php, inc/exception/fusioninventoryruleinconsistency.class.php, inc/fusioninventory.class.php, inc/invitation.class.php, setup.php, tests/suite-unit/PluginFlyvemdmFusionInventory.php, tests/suite-unit/PluginFlyvemdmInvitation.php
Automatically generate rules to "route" imported devices in the entity of  the invitation.
@rafaelje the tag in  the inventory must be similar to **invitation_4564546564587**.
I'm unsure how I described you the tag on telegram (underscore or dash). We need to check and use the same !
=> Fix invited devices are always created in root entity

install/policies/deployment.php, install/policies/phone.php
The policy was in the bad category, and it is better to disallow unknown sources with the same mechanism as disable Bluetooth.
- if Disable Unknown Sources is applied with the value *Yes** then the agent must forbid the user from enabling unknown sources
- if Disable Unknown Sources is applied with the value **No**  then the agent must do nothing (allowing the user to freely enable or disable the unknown sources)
- if Disable Unknown Sources is not applied,  then the agent must do nothing  (allowing the user to freely enable or disable the unknown sources)
=> Move and reverse unknown sources policy

inc/policybase.class.php, inc/policydeployapplication.class.php, inc/policydeployfile.class.php, inc/policyinterface.class.php, inc/task.class.php, tests/src/Flyvemdm/Tests/CommonTestCase.php
For application / file deployment tasls.
When the administrator unapplies an app / file deployment task, and this task has remove_on_delete set, the delete app / file task must send its MQTT message **after** the null MQTT message
The purpose is to make more consistent the MQTT messages incoming to the agent. It is a non sense to receive aa removal message for something which must be installed (because the install message is not yet canceled)
enhances #487
=> Reorder cascaded task creation

install/installer.class.php, install/policies/userInterface.php, install/upgrade/update_to_dev.php
Add missed code for the PR #509
=> Patch for PR of OS min/max versions

tpl/computer_geolocation.html.twig
Hi, @flyve-mdm/backend-development 
In this PR I include these changes:
- Edit datetime format for beginDate parameter
- Edit datetime format for endDate parameter
The bug is caused by that PHP can't create a datetime from string with format:
> Fri Apr 06 2018 19:48:48 GMT-0400 (-04)
This generate a error 500 in:
`new DateTime('Fri Apr 06 2018 19:48:48 GMT-0400 (-04)');`
Shorten datetime string to 33 characters.
Closes #499
=> Fix for marks on geolocation map

inc/graph.class.php
Hi, @flyve-mdm/backend-development.
For fix the issue i change the query when i get the computers. The labels repeated was be caused by the version field in the groupby.
This is the Dashboard after the modification:
|:---|:---:|
|@ingluife |3|
Closes #559 
Related #535
=> WIP Fix labels repeated

tpl/computer_geolocation.html.twig
Hi, @flyve-mdm/backend-development.
I changed the way of formated the Datetime corresponding to beginDate and endDate when get the agent geolocations.
I used the **toISOString()** for avoid use slice method in javascript.
This is a documentation of the method:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
|:---|:---:|
|@ingluife |1|
Closes #499
Related #541
=> WIP Change datetime format in request

inc/entityconfig.class.php, tpl/config-wizard.html.twig
Some strings in the wizard shall not be localized because they mention non localizable text (Fusion Inventory configuration)
Also fix a bad source string, making all langauges loose 1 translation string  :(
|:---|:---:|
|@btry |1|
=> Remove localization for strings which should not localized

css/style.css, inc/policybase.class.php, inc/policyboolean.class.php, inc/policydeployapplication.class.php, inc/policydeployfile.class.php, inc/policydropdown.class.php, tests/suite-unit/PluginFlyvemdmPolicyBase.php, tpl/fleet_policy.html.twig, tpl/policy_value.html.twig
Hi, @flyve-mdm/backend-development.
Refactor in policy add and update. Use twig template engine for policy value. Edit showValueInput methods of classes corresponding to each value type.
Add policy - Deploy file:
Add policy - Deploy Application
Update policy - Deploy file
Related #308
=> Render policy value with Twig

tests/src/Flyvemdm/Tests/CommonTestCase.php, tests/suite-unit/PluginFlyvemdmPolicyBase.php, tests/suite-unit/PluginFlyvemdmPolicyBoolean.php, tests/suite-unit/PluginFlyvemdmPolicyDeployapplication.php, tests/suite-unit/PluginFlyvemdmPolicyDeployfile.php, tests/suite-unit/PluginFlyvemdmPolicyDropdown.php, tests/suite-unit/PluginFlyvemdmPolicyInteger.php, tests/suite-unit/PluginFlyvemdmPolicyRemoveapplication.php, tests/suite-unit/PluginFlyvemdmPolicyString.php
Better unit tests 
we must not directly set $object->fields in an object.
this property must be considered private. Someday it will.
Generalize tests on task statuses
|:---|:---:|
|@btry |2|
Closes #N/A
Related #N/A
=>  Enhance status tests

.travis.yml
Allowed failures are not taken into account in Travis. This fix should solve the issue
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A
=> Fix allowed failures

inc/agent.class.php, tests/suite-integration/PluginFlyvemdmAgent.php
Serial and uuid are no longer used in enrolment. These data are in the inventory and the creation of the computer is delegated to this plugin.
=> Remove obsolete requirements

install/policies/mdm.php, tests/src/Flyvemdm/Tests/CommonTestCase.php
This feature requires care about privacy. Other policies must be created to cover these concerns.
Send a periodic geolocation to the backend. Delay in seconds.
To disable the feature the agent must detect the absence of this policy when it connects again, or a null message on the topic of the policy. Both cases must disable the periodic geolocation .
Do NOT merge before aproval from @rafaelje (his technical requirements may impact the implementation of the feature server side) 
Signed-off-by: Thierry Bugier <tbugier@teclib.com>
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A
=> Add (basic) periodic geolocation

tests/after_success.sh, tests/apidocs.sh
I detected a problem showed at the image when the documentation is generated by CI
The idea for this PR is to solve the problem forcing the checkout of gh-pages
|:---|:---:|
|@DIOHz0r |8|
Closes #N/A
Related #N/A
=> Fix ci script for update gh-pages

inc/agent.class.php, inc/fleet.class.php, inc/policy.class.php, inc/wellknownpath.class.php
When we use the search engine, it must use only "is" (also "is not", but this is not necessary IMO for a bool) operator for search criterias. 
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A
=> Restrict operator for boolean search options

inc/mqtthandler.class.php
I noticed in this screenshot an issue with the date of the log entries
now timestamp is consistent with the actual time of the event
|:---|:---:|
|@btry |1|
=> Fix date log

inc/agent.class.php
When the plugin creates a user for the mdm agent the user does not has a password. This is needed to consume the rest API.
|:---|:---:|
|@btry  |1|
Closes #N/A
Related #N/A
=> Give a pasword to the agent user account

inc/agent.class.php, tests/suite-integration/PluginFlyvemdmAgent.php
This reverts commit d398594e8950e8818b8e81edac4cfb793cebc45d.
i did a mistake: we already generate a api token at the end of enrollment for  the agent machine user. No need to store the password; let's use this token
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A
=> Revert "feat(agent): give a pasword to the agent user account"
