flyve-mdm/glpi-plugin

.travis.yml

This Travis CI bot can notify you about builds of your repositories on Telegram.
https://storebot.me/bot/travisci_build_bot

build(ci): add notifications for audit trail

---

inc/agent.class.php
inc/fleet_policy.class.php

A count is missing in a tab, use plurals

feat(ui): improve count of items in tabs

---

inc/agent.class.php
inc/mqtthandler.class.php
install/mysql/plugin_flyvemdm_empty.sql
install/upgrade/update_to_dev.php
tests/0010_Integration/HandleIncomingMqttMessageTest.php

Feature extracted from #50 
use will and testament to maintain online status of devices

Maintain online status of devices

---

inc/file.class.php
inc/package.class.php

avoid download of files from an other mean than the API

Restrict file and package download to the API only

---

front/agent.php
inc/agent.class.php
inc/common.class.php
inc/profile.class.php
setup.php

Code refactor, single quotes, and cleanup some dead code

Refactoring plugin initialization

---

inc/agent.class.php
tests/0010_Integration/PluginFlyvemdmAgentIntegrationTest.php

Unlock devices feature

---

inc/mqtthandler.class.php

JSONified version in Flyvemdm Manifest MQTT topic

publish version in JSON object

---

inc/taskstatus.class.php

Fix header

---

inc/invitation.class.php
inc/notificationtargetinvitation.class.php

re-use base64_encode for enrollment

fix(enrollment): re-add base64_encode

---

inc/entityconfig.class.php
inc/file.class.php
inc/fleet.class.php
inc/geolocation.class.php
inc/mqttclient.class.php
inc/mqtthandler.class.php
inc/mqttlog.class.php
inc/mqttupdatequeue.class.php
inc/mqttuser.class.php
inc/policyinterface.class.php
inc/profile.class.php
inc/wellknownpath.class.php

Refactoring and code cleanup

---

.travis.yml
inc/agent.class.php
tests/suite-integration/PluginFlyvemdmAgent.php

this is #117 with a rewritten history

Dio hz0r develop

---

plugin.xml

the repository URL changed, but the .xml file was not updated

fix: update plugin.xml

---

inc/package.class.php

Hi, @btry 
This is a solution for refactor the package upload code from the issue #126 
Best regards.

Refactor package upload code

---

inc/package.class.php

count of updates will be more accurate

fix(package): take into account update success when parsing an application

---

inc/package.class.php
install/installer.class.php
install/mysql/plugin_flyvemdm_empty.sql
install/upgrade/update_to_dev.php

Use the Orion plugin to request analysis from the remote Orion service
Needs additional UI to shwow the report

Use Orion server if possible

---

inc/mqttclient.class.php
inc/package.class.php
install/mysql/plugin_flyvemdm_empty.sql
install/upgrade/update_to_dev.php

Fix #149
Also fix an upgrade  problem

Path to file to parse

---

setup.php

Backward compatibility of prerequisite checks

---

inc/config.class.php

code to generate HTML for the field was not moved

field to upload CA certificate file

---

inc/task.class.php

I found a method which is never used.

Remove unused method

---

setup.php
tpl/computer_geolocation.html

leaflet reported broken in #147

fix leaflet

---

inc/agent.class.php
inc/invitation.class.php
inc/mqtthandler.class.php
inc/mqttupdatequeue.class.php

Hi,
This Pull Request is for fix the issue 92 about the date time zone difference between the plugin and the GLPI.
Regards.

Datetime zone fix

---

install/installer.class.php
install/upgrade/update_to_dev.php
tests/suite-integration/ProfileRight.php

Hello,
This changes is for allow the super admin to update invitations. 
This fixed issue #84 
Regards.

[WIP] Allow super-admin to update invitation

---

install/installer.class.php

Remove a half-duplicate policy

---

.github/PULL_REQUEST_TEMPLATE.md
.github/invite-contributors.yml

Hi, @ajsb85 
This PR adds the pull request template and the file to auto invite contributors

Documentation

---

install/installer.class.php

Add policy for airplane mode

---

inc/agent.class.php
inc/common.class.php
tests/suite-integration/PluginFlyvemdmAgent.php

When a device is trying to enroll the username could exist because its login is the serial number from the device.
Fixes #177 
The agent user account now has a unique id.

Set unique agent account name.

---

inc/agent.class.php

fix #179
added *mdm type*, **enroll status* and *has system permission*.

Update search options

---

README.md

Links of Documentation and Installation are out date, they refer to the wiki in the repository
Issue #N/A
The links are updated, they now refer to their respective sections in the project site

Update links in the Readme file

---

.travis.yml
inc/policyinteger.class.php
tests/suite-integration/PluginFlyvemdmAgent.php
tests/suite-unit/PluginFlyvemdmCommon.php
tests/suite-unit/PluginFlyvemdmPolicyBase.php
tests/suite-unit/PluginFlyvemdmPolicyBoolean.php
tests/suite-unit/PluginFlyvemdmPolicyCategory.php
tests/suite-unit/PluginFlyvemdmPolicyDeployfile.php
tests/suite-unit/PluginFlyvemdmPolicyDropdown.php
tests/suite-unit/PluginFlyvemdmPolicyInteger.php
tests/suite-unit/PluginFlyvemdmPolicyString.php

There are a lot of missing unit tests
New unit test for the plugin

[WIP] Tests additions and upgrades

---

css/style.css
inc/geolocation.class.php
tpl/computer_geolocation.html

Hello,
This Pull Request is for the feature of issue #133 
Regards.

OpenStreetMap UI updates

---

inc/mqttclient.class.php

Fix ability for the backend to send mqtt messages after enhancement of the settigns.

Use good config vars to connect to broker

---

inc/mqttclient.class.php

Logs a message if configuration is damaged; and fix its check.

Configuration check when sending a message

---

inc/mqttclient.class.php

Connection to backend

---

inc/agent.class.php
inc/package.class.php
tests/suite-integration/PluginFlyvemdmAgent.php

Fix computer type affectation in enrollment process

---

install/installer.class.php

Hi @DIOHz0r @rafaelje 
I let you choose when you want to merge this PR.

Harmonize policies

---

install/installer.class.php

Hi
@rafaelje @DIOHz0r 
I let you choose when you want to merge it.

Typo in symbol name of a policy

---

.github/CONTRIBUTING.md
README.md

The links of the repo name are out of date
The links in the build status section are out of date
Issue #N/A
Links fixed

Change links in project documentation

---

install/installer.class.php
install/upgrade/update_to_dev.php

After an upgrade packages could not be downloaded

Upgrade should not modify package file path more than once

---

front/file.form.php

Fix a right check issue when adding a file from the UI
Workaround a var conflict with GLPI (by renaming it). To be reported to GLPI team.

Fix file upload for glpi ui

---

.travis.yml
inc/invitation.class.php
tests/suite-integration/PluginFlyvemdmInvitation.php

Incompleted test for invitation class
Issue #N/A
New and updated test integration for invitations.
The CI script is also updated for BC with forked repos.

Updated tests for invitation

---

inc/agent.class.php
setup.php
tests/suite-integration/PluginFlyvemdmAgent.php
tpl/_agentInfo.html
tpl/agentComputerInfo.html
tpl/agentComputerTab.html

Issue #218 
New tab added for computer UI

Added Flyve MDM Agent tab to computer UI

---

inc/policydeployfile.class.php

Issue #231 
This allows change allows different files at same folder destination.

Allow different files at same destination

---

inc/package.class.php
inc/policydeployapplication.class.php
install/mysql/plugin_flyvemdm_empty.sql
install/upgrade/update_to_dev.php
tests/suite-integration/Entity.php
tests/suite-integration/PluginFlyvemdmPackage.php
tests/suite-unit/PluginFlyvemdmPolicyDeployapplication.php
tpl/package.html

Proposal to fix #232. See my latest comment on the issue.

Improve UX by allowing to send package name

---

RoboFile.php
package.json

I improved the build tool of Formcreator to generate the changelog automatically. Let's push this work in this plugin too.
TODO: tidy the robo script...

Improve build tool

---

inc/config.class.php
install/installer.class.php
install/upgrade/update_to_dev.php
locales/flyvemdm.pot
setup.php
tests/suite-unit/PluginFlyvemdmAgent.php
tests/suite-unit/PluginFlyvemdmConfig.php
tpl/config-applemdm.html
tpl/config-debug.html
tpl/config-wizard.html

Functional draft of the installation wizard
See #154

Template for installation wizard

---

inc/agent.class.php
tests/src/TestingCommonTools.php

The XML from the agents on the enrollment process comes in raw format, when it was read by GLPI special characters of nodes were escaped.
Issue #255 
XML now is encoded to fix the enrollment.

Inventory XML needs to be decoded

---

inc/agent.class.php
tests/src/TestingCommonTools.php

Issue #255 
The string from inventory is now decoded as XML

Removed base64 encoding for XML inventory

---

tpl/config-wizard.html

Fix inconsistencies in the wizard

Fix errors in wizard

---

inc/agent.class.php

On failure enrollment some times the user agents are created
Fixes #258 
The user agent are now created at almost the end of the process.

Not allow to register invalid user agents

---

inc/agent.class.php
tests/src/TestingCommonTools.php

XML of inventory doesn't import on enrollment
Fixes #257 
The FI is now reloaded for importing XML
The flyvemdm/backend-test lib must be updated to emulate the correct session behavior from GLPI

Reload FusionInventoy plugin for enrollment

---

_includes/header.html
build/tests/coverage/index.html

Issue #250 
New page for code coverage

Page for code coverage

---

tpl/config-wizard.html

Text of the install wizard is misspelled
New help text

Install wizard text update

---

inc/agent.class.php
inc/file.class.php
inc/fleet.class.php
inc/package.class.php
inc/policy.class.php
inc/wellknownpath.class.php

Fixes #276,  Closes #277 
All ItemTypes show ID field and uses main core logic for default fields

Search fields updated

---

plugin.xml

Fixes #273 
Updated information

Updated plugin XML

---

tpl/config-wizard.html

fix a typo and improve the wizard

Text of the wizard updated

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/settings.yml

Issue #N/A
* Improve the following documentation:
* Contributing guidelines
* Issue template
* PR template
* Add YAML file for bot settings

Improve documentation

---

tests/suite-integration/PluginFlyvemdmTask.php

Improve unit tests for policies

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

- The commit message follows our guidelines: [Conventional Commit](https://conventionalcommits.org/)
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)
Issue #N/A

New issue and Pull-Request templates

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/settings.yml

Improvements to issue and PR template
Closes #N/A

Issue & PR template improvements

---

inc/agent.class.php

Code simplification; remove a useless else {] clause.

Remove useless else {}

---

install/installer.class.php

fix #290
add a policy to setup recurrent inventory
Closes #290

New policy for inventory frequency

---

inc/config.class.php
tests/before_script.sh
tests/patches/fi_master_patch.diff
tpl/config-wizard.html

Add new step for Fusion Inventory configuration
Rename the cron job step, it used to be REST API too
Change order of step from Email notifications > REST API > Cron job
to Email notifications > Cron job > REST API
Add new set of pages for previous requirements
Reference #287 
#

Wizard enhancement

---

_layouts/coverage.html

Fix the header display
Closes #300

Add coverage layout

---

install/installer.class.php
install/upgrade/update_to_dev.php

fix #298
PascalCase to camelCase
must solve https://github.com/flyve-mdm/android-mdm-agent/issues/285 before merging this one (WIP kept for this purpose)
Closes #298

Fix not camelCase policies

---

.github/push_ghpages.sh

Bad layout assigned to the coverage report
Closes #304

Fixed coverage layout

---

.github/push_ghpages.sh

The PR #305 has a bad directory name, this change fixes it.
Closes #304

Patch for report layout

---

ajax/policyValue.php
front/task.form.php
inc/policybase.class.php
inc/policyboolean.class.php
inc/policydeployapplication.class.php
inc/policydeployfile.class.php
inc/policydropdown.class.php
inc/policyfactory.class.php
inc/policyinterface.class.php
inc/task.class.php
inc/wellknownpath.class.php
tests/suite-integration/PluginFlyvemdmFile.php
tests/suite-unit/PluginFlyvemdmPolicyBoolean.php
tests/suite-unit/PluginFlyvemdmPolicyDeployapplication.php
tests/suite-unit/PluginFlyvemdmPolicyDeployfile.php
tpl/fleet_policy.html
tpl/policy_form.html

This feature adds the option to edit the value of a created policy for a fleet
Closes #239

Edit created policies

---

inc/task.class.php
tests/suite-integration/PluginFlyvemdmTask.php

Non unique tasks overwrite each other

---

.travis.yml
inc/agent.class.php
scripts/mqtt.php
tests/before_install.sh
tests/suite-install/Config.php
tests/suite-integration/PluginFlyvemdmAgent.php
tests/suite-unit/PluginFlyvemdmAgent.php
tools/cli_install.php

fix wrong merge of two arrays
Closes #285

Some MQTT topics are not cleaned up

---

composer.json
composer.lock

Add composer.lock, because this repo is a project.
Force packages selection to be compliant with the lowest version of PHP supported by GLPI and this plugin.

Re-add composer.lock

---

.github/push_ghpages.sh

Removed CSS from coverage report to use the styles of the project site.
Closes #321

Fix coverage report styles

---

CONTRIBUTING.md

a better guide for issue/bug report
a clearer branch creation guide
get rid of the header table
less emojis
Closes #N/A

WIP Better guide for issue report and branching

---

tests/before_script.sh
tests/config-composer.sh

Update code for Travis before_script to not remove the composer.lock and been able to test for different PHP versions env according to this post https://hannesvdvreken.com/2015/01/18/composer-ignore-platform-reqs-flag/
Patch related to PR #325

Patch for before script code

---

front/file.form.php
inc/common.class.php
inc/file.class.php
install/installer.class.php
install/mysql/plugin_flyvemdm_empty.sql
install/upgrade/update_to_dev.php
tests/bootstrap.php
tests/suite-unit/PluginFlyvemdmFile.php
tests/suite-unit/PluginFlyvemdmPolicyDeployfile.php
tpl/file.html

Rebase #317 and enhancements
WIP : need to check unit tests for prepareInputForAdd and prepareInputForUpdate of the PluginFlyvemdmFile
Add a comments field for files

Add comment field

---

index.html

The information in the index is out of date, it currently has the old installation instructions
Closes #N/A

Change index information

---

tpl/config-wizard.html

Fix inconsistencies in wizard

---

CONTRIBUTING.md

add information about app/bot that checks PR
fix broken links
add information about commit character length
more information about how to work with WIP on PR
erase an irrelevant phrase on a description
regular proofreading check
add info about status checks
include a note about requirements
add new sections
Closes #N/A

Add information about app/bot that checks PR

---

inc/config.class.php
inc/menu.class.php
setup.php
tpl/config-wizard.html
tpl/menu.html

Add a missing step in the wizard, move the GLPI configuration requirement checks
If GLPI seems not properly configured, a text is displayed above the UI. May be enhanced for a nicer display.
Closes #333

Maximize wizard use of the wizard

---

front/entityconfig.form.php
hook.php
inc/agent.class.php
inc/entityconfig.class.php
inc/invitation.class.php
inc/notificationtargetinvitation.class.php
inc/profile.class.php
install/installer.class.php
tests/suite-integration/Entity.php
tests/suite-integration/ProfileRight.php

- Create a method to check the device count limit
- Rrename PluginFlyvemdmEntityconfig to PljginFlyvemdmEntityConfig
2nd change is related to a very old discussion about class naming convention with GLPI team, and usual naming conventions for classes.

Move device limit checking

---

install/mysql/plugin_flyvemdm_empty.sql

Old product name lying in SQL file

Obsolete comment in SQL file

---

package.json

build: update packages

---

CONTRIBUTING.md

fix errors in punctuation
add a "Go to top" feature
Closes #N/A

Fix errors in punctuation

---

_posts/static/2017-11-14-mqtt-messages-specifications.md

Update mqtt messages and topics

---

_includes/header.html
development/specifications/index.md

Add new sub-item in the development section
Closes #347

New sub-item Specifications

---

install/upgrade/update_to_dev.php

script for update the plugin throws PHP waring, this patch fix the output
Related with PR #310

Fix for upgrade script

---

_posts/static/2017-11-14-use-cases.md
_posts/static/2017-11-15-how-it-works.md
_posts/static/2017-12-21-how-to-translate.md
_posts/static/2018-01-24-upgrade-flyve-mdm-plugin.md
_posts/static/2018-02-01-installation-wizard.md

add compatibility matrix to installation and upgrade articles
improve content and titles
Closes #352
Reference #345

Improve articles

---

_posts/static/2018-02-01-installation-wizard.md

Add exception to the step in GLPI installation after issue and conversation in Dev group in Telegram
Reference [#3639](https://github.com/glpi-project/glpi/issues/3639)

Installation exception

---

_includes/head.html
css/coverage.css

Move footer to correct position
Closes #356

Fix footer in coverage

---

inc/common.class.php
inc/file.class.php
inc/package.class.php
install/mysql/plugin_flyvemdm_empty.sql
install/upgrade/update_to_dev.php
tests/suite-integration/Entity.php
tests/suite-integration/PluginFlyvemdmPackage.php
tests/suite-integration/PluginFlyvemdmPolicyRemoveApplication.php
tests/suite-unit/PluginFlyvemdmCommon.php
tests/suite-unit/PluginFlyvemdmFile.php
tests/suite-unit/PluginFlyvemdmPackage.php
tests/suite-unit/PluginFlyvemdmPolicyDeployapplication.php

Upgrade code to show filesize info for files and packages
Closes #176

Add filesize information

---

_posts/static/2018-02-01-installation-wizard.md

Add folder name to git commands to rename the folder directly, from the Telegram chat Flyve MDM Dev
Closes #N/A

Git clone commands in installation article

---

tpl/config-wizard.html.twig

Fix typo in FI step, from Telegram chat Flyve MDM Dev
Closes #N/A

Fix typo in wizard

---

_posts/static/2018-02-20-workflow.md
_sass/_general.scss
index.html

Add workflow information on main page and article
Closes #N/A

Workflow information

---

tpl/config-wizard.html.twig

Change ip for hostname to test mosquitto connection
Closes #N/A

Correct TLS step

---

inc/agent.class.php
inc/config.class.php
inc/fleet.class.php
inc/invitation.class.php
inc/mqtthandler.class.php
inc/mqttuser.class.php
inc/policy.class.php
inc/wellknownpath.class.php
install/installer.class.php
setup.php
tests/before_script.sh
tests/patches/fi-master.patch
tests/suite-integration/Entity.php
tests/suite-integration/PluginFlyvemdmAgent.php
tests/suite-integration/PluginFlyvemdmFile.php
tests/suite-integration/PluginFlyvemdmFleet.php
tests/suite-integration/PluginFlyvemdmInvitation.php
tests/suite-integration/PluginFlyvemdmMqttuser.php
tests/suite-integration/PluginFlyvemdmPackage.php
tests/suite-integration/PluginFlyvemdmPolicyDeployFile.php
tests/suite-integration/PluginFlyvemdmPolicyRemoveApplication.php
tests/suite-integration/PluginFlyvemdmPolicyRemoveFile.php
tests/suite-integration/PluginFlyvemdmTask.php
tests/suite-unit/PluginFlyvemdmFile.php
tests/suite-unit/PluginFlyvemdmPackage.php

fix #365 
This PR requires https://github.com/glpi-project/glpi/pull/3724

Fix deprecated GLPI methods calls

---

inc/policyboolean.class.php
inc/policydeployapplication.class.php
inc/policydeployfile.class.php

Code refactor of the policies for better reading
Closes #N/A

Update code for better reading

---

front/agent.form.php
front/agent.php
front/config.form.php
front/file.form.php
front/file.php
front/fleet.form.php
front/fleet.php
front/invitation.form.php
front/invitation.php
front/package.form.php
front/package.php
inc/menu.class.php
tpl/menu.html.twig

Add dropdown menu to all main itemtypes of the plugin.
Closes #362

Add menu to main itemtype displays

---

inc/mqtthandler.class.php

Code refactor from the policies feedback PR.
To be validated after rebase of the other pending code refactor

Simplify code

---

inc/mqtthandler.class.php

Flyve manifest topic had 2 problems
* infinite loop when updating the version if Flyve in the manifest
* leading slash in the topic not removed here in  the previous leading slash removal PR

Fix manifest malfunction

---

.travis.yml
inc/agent.class.php
inc/mqtthandler.class.php
inc/policybase.class.php
inc/policydeployapplication.class.php
inc/policydeployfile.class.php
inc/policyinteger.class.php
inc/policyremoveapplication.class.php
inc/policyremovefile.class.php
inc/task.class.php
inc/taskstatus.class.php
tests/bootstrap.php
tests/src/Glpi/Tests/CommonTestCase.php
tests/suite-integration/Entity.php
tests/suite-integration/PluginFlyvemdmTask.php
tests/suite-unit/PluginFlyvemdmPolicyBase.php
tests/suite-unit/PluginFlyvemdmPolicyBoolean.php
tests/suite-unit/PluginFlyvemdmPolicyDeployapplication.php
tests/suite-unit/PluginFlyvemdmPolicyDeployfile.php
tests/suite-unit/PluginFlyvemdmPolicyInteger.php
tests/suite-unit/PluginFlyvemdmPolicyString.php
tpl/agent_taskstatus.html.twig
tpl/fleet_taskstatus.html.twig

refactor post_updateItem by splitting its content and reordering its actions
Closes #N/A

Policies feedback (v2)

---

install/upgrade/update_to_dev.php

Use migration object to update configuration

---

inc/notificationtargetinvitation.class.php

Fix a invalid token string on invitation caused by a wrong word typing 
Closes #392

Hotfix for invitation token

---

inc/config.class.php
setup.php
tpl/config-debug.html.twig

Show the revision from GIT, if available. For development and debug purpose.

Show development revision in debug settings

---

inc/fleet.class.php
tests/suite-unit/PluginFlyvemdmFleet.php

fix fleet deletion & drop dead code

---

install/upgrade/update_to_dev.php

Fix bad MQTT messages in the upgrade to development version

Fix malformed MQTT messages when chagning topic layout

---

inc/policydeployapplication.class.php

Should use the same implementation as File deployment policy

Harmonize unapply method of Package deployment policy

---

inc/fleet.class.php
tests/suite-unit/PluginFlyvemdmFleet.php

One may change the recursion of a managed fleet

Allow recursion change for non default fleets

---

tests/suite-unit/PluginFlyvemdmFleet.php

Drop useless method for unit tests

---

inc/agent.class.php

Make code simpler

---

inc/config.class.php
inc/menu.class.php

I noticed the configuration menu does not opens the good tabs. 
Here is the fix

Fix tab number

---

tests/suite-unit/PluginFlyvemdmFleet.php

Fix failed unit test for fleets
Closes flyve-mdm/glpi-plugin#409

Update unit test for fleet

---

setup.php

the package ID changed for the android mdm agent

Update the android app package id

---

inc/entityconfig.class.php
tests/src/Glpi/Tests/CommonTestCase.php
tests/suite-unit/PluginFlyvemdmEntityConfig.php

Do not silently fail to update entity config

---

tests/src/Flyvemdm/Tests/CommonTestCase.php
tests/suite-integration/PluginFlyvemdmAgent.php
tests/suite-integration/PluginFlyvemdmFile.php
tests/suite-integration/PluginFlyvemdmPackage.php
tests/suite-integration/PluginFlyvemdmPolicyDeployFile.php
tests/suite-integration/PluginFlyvemdmPolicyRemoveFile.php
tests/suite-integration/PluginFlyvemdmTask.php
tests/suite-unit/PluginFlyvemdmPolicyRemoveapplication.php

code factorization in unit tests

Mutualize helper method

---

inc/config.class.php
tpl/config-wizard.html.twig

Add document type step to wizard
Closes #345

Document type step

---

.travis.yml
hook.php
inc/menu.class.php
inc/policydeployapplication.class.php
inc/policydeployfile.class.php
inc/policyinterface.class.php
inc/policyremoveapplication.class.php
inc/task.class.php
tests/suite-integration/PluginFlyvemdmFile.php
tests/suite-integration/PluginFlyvemdmPackage.php
tests/suite-integration/PluginFlyvemdmPolicyDeployFile.php

Picked code refactors from the dependency injection branch

Code refactor

---

tests/suite-unit/PluginFlyvemdmEntityConfig.php

Add unit tests

---

inc/policy.class.php

- some search optiosn were missing
- use flyvemdm domain for locales

Add missing search options

---

install/installer.class.php
tests/suite-unit/PluginFlyvemdmAgent.php

Added policy for disable all sounds on device
Closes #406

Disable all sounds policy

---

inc/agent.class.php
tests/suite-integration/PluginFlyvemdmAgent.php

Getting an agent by topic failed

---

locales/es_ES.po
locales/es_MX.po

Add translations for Spanish (Mexico and Spain)

Support for spanish language

---

inc/mqtthandler.class.php

Again: an issue  popped when we dropped the leading slash.

Fix handling inventory

---

inc/agent.class.php

Add informative message
@Gianfranco97 ping

Send informative notification for manual actions

---

ci/tets-jekyll.sh

The CI biuld fails checking the external links even if they are working, let's remove that check for now.
Closes #452

Remove check for external links

---

setup.php
tests/patches/fi-raise-max-version.patch

FI patch ws incomplete

---

install/installer.class.php

Related to my comment on https://github.com/flyve-mdm/glpi-plugin/pull/456

Some strings shall not be translated

---

inc/invitation.class.php

@Gianfranco97 @hectorerb 
This PR changes a search option ID. Please check  the impact on the dashboard.

Better column name and allow view of invitations

---

inc/invitation.class.php
install/installer.class.php
install/mysql/plugin_flyvemdm_empty.sql
install/upgrade/update_to_dev.php

Give a column for name and add display preferences

Enhnance again UI

---

ajax/policyValue.php
hook.php
inc/agent.class.php
inc/fleet.class.php
inc/mqtthandler.class.php
inc/notifiableinterface.class.php
inc/package.class.php
inc/policy.class.php
inc/policybase.class.php
inc/policydeployapplication.class.php
inc/policydeployfile.class.php
inc/policyinterface.class.php
inc/policyremoveapplication.class.php
inc/policyremovefile.class.php
inc/task.class.php
inc/taskstatus.class.php
install/mysql/plugin_flyvemdm_empty.sql
install/upgrade/update_to_dev.php
tests/src/Flyvemdm/Tests/CommonTestCase.php
tests/suite-integration/PluginFlyvemdmAgent.php
tests/suite-integration/PluginFlyvemdmFile.php
tests/suite-integration/PluginFlyvemdmFleet.php
tests/suite-integration/PluginFlyvemdmPackage.php
tests/suite-integration/PluginFlyvemdmPolicyDeployFile.php
tests/suite-integration/PluginFlyvemdmPolicyRemoveFile.php
tests/suite-integration/PluginFlyvemdmTask.php
tpl/fleet_policy.html.twig
tpl/fleet_taskstatus.html.twig
tpl/policy_form.html.twig

The PR seems to work well. I still need to check it in a functional PoV, and add unit tests.
Sorry, there are some random changes (refactor, typos, other things not really related to the feature)

WIP Policies on devices 2

---

install/policies/mdm.php
install/policies/peripherals.php

The periodic inventory should go in MDM

A policy has a wrong category

---

install/upgrade/update_to_dev.php

Code update for the cli_install script which shows an error about a missing column name when it updates the DB schema.

Hotfix for install script

---

tests/before_script.sh
tests/patches/fi-master-search-options.patch

Patch to solve the exception messages thrown by FI master branch on our CI

Patch for CI problems with FI master branch

---

css/style.css
inc/agent.class.php
inc/package.class.php
install/installer.class.php

Fix display preferences definition,
add display prefs for packages, and fix display of icon in list of packages
@Gianfranco97 I notify you, maybe you're interested about this UI ability. Note that the icon should be sent to you as raw data (png format)
Parts if code picked from Fdroid PR
(and buggy display)

Add display preferences

---

RoboFile.php

i moved the policies definition in specific files but Robo script does not handle them. Fixing here

Include policies files in locales extraction

---

install/policies/phone.php
tests/suite-install/Config.php
tests/suite-unit/PluginFlyvemdmAgent.php

Add a policy for allow the installation of unknown apps
Closes #463

Policy for unknown sources

---

inc/mqtthandler.class.php
inc/policydeployapplication.class.php
inc/policydeployfile.class.php

closes #484 
Please @DIOHz0r @rafaelje test this.

Fix message not sent on cascaded creation of task

---

.travis.yml
install/policies/userInterface.php
tests/before_install.sh
tests/src/Flyvemdm/Tests/CommonTestCase.php
tests/suite-install/Config.php
tests/suite-unit/PluginFlyvemdmAgent.php

This PR remove the disableAllPolicy, update the test code and update Travis script to use the apt addon.

Update for policies and travis

---

install/installer.class.php
install/policies/mdm.php

A time interval cannot have a negative value

Fix negative number

---

inc/mqtthandler.class.php
inc/task.class.php
tests/suite-unit/PluginFlyvemdmEntityConfig.php

Fix bugs in task status feedback handling

---

tools/cli_install.php

Fix warning with PHP 7.2

---

inc/fleet.class.php
tpl/fleet.html.twig

Show whether a fleet is managed or not

---

ajax/geolocation.php
ajax/getGraph.php
ajax/mqtt_test.php
ajax/policyValue.php
front/agent.form.php
front/agent.php
front/config.form.php
front/entityconfig.form.php
front/file.form.php
front/file.php
front/fleet.form.php
front/fleet.php
front/invitation.form.php
front/invitation.php
front/package.form.php
front/package.php
front/policycategory.form.php
front/policycategory.php
front/task.form.php
front/wellknownpath.form.php
front/wellknownpath.php
inc/file.class.php

May be merged for 2.0, it depends on the approval date

Include is not a function / search options alignement

---

tests/bootstrap.php
tests/src/Glpi/Tests/CommonTestCase.php
tests/suite-install/Config.php

This is an attempt to cleanup tests. Let's see if this has an impact

Cleanup attempt

---

install/upgrade/update_to_dev.php

Fix for script which updates dev. DB schema.
Ref #502

Migration update

---

tpl/config-wizard.html.twig

Improve wizard:
Add new rules to disable in Fusion Inventory configuration
Closes #N/A

Add new rules to disable for FI configuration in Wizard

---

inc/task.class.php

Add the option to display new task fields on search results.
Closes #513

New fields to display on search

---

tpl/config-wizard.html.twig

Tell the db name should be customized

---

inc/policy.class.php
inc/task.class.php

Enhance dropdown when applying policies

---

tpl/agent_fleet.html.twig

I found a missing if for paging handling in GLPI UI.

Fix paging

---

inc/policydeployapplication.class.php
inc/policydeployfile.class.php
tpl/policy_deploy_app_form.html.twig
tpl/policy_deploy_file_form.html.twig

Create new twig files for the deploy policies
More changes to come
Closes #493

Replace raw HTML with Twig for deploy policies

---

install/policies/mdm.php
install/policies/password.php
install/policies/peripherals.php
install/policies/phone.php
install/policies/userInterface.php
tests/src/Flyvemdm/Tests/CommonTestCase.php

This PR removes from the project the policies which are not ready for the release 2.0
/cc @DIOHz0r @rafaelje 
For convenience, please, remove yourself any policy that you want to remove, one per commit. Doing so will allow us to revert a commit to re-add the policy after the release.

Remove not ready policy

---

install/upgrade/update_to_dev.php

This changes update the upgrade script for installed plugin
Pull Request #495

Patch for upgrade installation

---

inc/policy.class.php
inc/task.class.php

also adds empty choice to ensure no policy selected and good init of extra fields
closes #536

Policies dropdown on GLPI UI

---

.travis.yml
composer.json
inc/agent.class.php
inc/common.class.php
setup.php
tests/before_script.sh
tests/patches/glpi-allow-test-on-master-branch.patch
tests/src/Flyvemdm/Tests/CommonTestCase.php
tests/suite-unit/PluginFlyvemdmCommon.php

Add additional XML parse tries to avoid format import problems on device enrolment

Checks of XML format on enrollment

---

inc/graph.class.php
tpl/menu.html.twig

Update for the graph of devices and OS on the dashboard 
Closes #535

Dashboard os version graph

---

install/upgrade/update_to_dev.php

A bug related with the search for the removed policies is finding only the fleets, the agents aren't notified so this PR solves it. 
This change also solve another performance problem sending only one notification through the broker.
raw query for you review:
``` SQL
SELECT
`glpi_plugin_flyvemdm_policies`.`symbol`,
`glpi_plugin_flyvemdm_tasks`.`id`,
`glpi_plugin_flyvemdm_tasks`.`itemtype_applied`,
`glpi_plugin_flyvemdm_tasks`.`items_id_applied`,
`glpi_plugin_flyvemdm_fleets`.`entities_id`
FROM `glpi_plugin_flyvemdm_policies`, `glpi_plugin_flyvemdm_tasks`, `glpi_plugin_flyvemdm_fleets`,
`glpi_plugin_flyvemdm_agents`
WHERE `glpi_plugin_flyvemdm_tasks`.`plugin_flyvemdm_policies_id` = `glpi_plugin_flyvemdm_policies`.`id`
AND `symbol` IN
('disableFmRadio', 'disableVoiceMail', …
```

Fix agent and fleet notification on upgrade

---

inc/agent.class.php
inc/common.class.php
tests/suite-integration/PluginFlyvemdmAgent.php
tests/suite-unit/PluginFlyvemdmCommon.php

Allow save the XML file for debug proposes on early steps of the enrol process.

Debug inventory file before enrol

---

ajax/geolocation.php
ajax/mqtt_test.php
inc/agent.class.php
inc/config.class.php
inc/entityconfig.class.php
inc/file.class.php
inc/fleet.class.php
inc/fusioninventory.class.php
inc/geolocation.class.php
inc/graph.class.php
inc/invitation.class.php
inc/mqtthandler.class.php
inc/notificationtargetinvitation.class.php
inc/package.class.php
inc/policy.class.php
inc/policydeployapplication.class.php
inc/policydeployfile.class.php
inc/task.class.php
inc/taskstatus.class.php
tpl/fleet_taskstatus.html.twig

New code refactor for the source code of the plugin
Ref #503

New code refactor

---

.github/PULL_REQUEST_TEMPLATE.md
.github/settings.yml
CONTRIBUTING.md

- PR template
add estimated time block in pomodoros
add new references to relate or dependecies
- Contributing guide lines
Add missing command
Add new issues url to respective sections
Add word feature in examples
Closes #N/A

Update Pull Request template & Contributing guidelines

---

composer.lock

The change is for update the vendors version used by our plugin
|:---|:---:|
|@diozh0r |1|
Closes #N/A

Update for vendors

---

_sass/_general.scss
index.html

|:---|:---:|
| @Vector-Blanxart |1|
Closes #N/A
Related #N/A

Fix styles project site

---

index.html

Resize and padding-top the image and padding-button the text
Before
After

Update project site's style

---

package.json

|:---|:---:|
|@ajsb85 |1|
|@diohz0r |1|
Closes #N/A
Related #N/A

WIP Update standard-version to version 4.4.0

---

locales/cs_CZ.po
locales/es_ES.po
locales/flyvemdm.pot
locales/fr_FR.po
locales/pt_BR.po
locales/ru.po

Update of misspelled and missing strings locales for all languages
|:---|:---:|
|@diohz0r |16|
Closes #583

Update locale translation

---

tests/suite-unit/PluginFlyvemdmCommon.php

Added tests for missing methods in common class
|:---|:---:|
|@DIOHz0r|9|
Related #N/A

New tests for Flyvemdm common class

---

locales/cs_CZ.po
locales/es_AR.po
locales/es_ES.po
locales/es_MX.po
locales/fr_FR.po

Update of Spanish translation for Spain, Mexico, Argentina, France and Czeh locales
|:---|:---:|
|@DIOHz0r |7|
Depends on #582

Update for translations

---

inc/graph.class.php
tpl/menu.html.twig

Before:
After:
Before (if no data for stats is available):
After: 
|:---|:---:|
|@DIOHz0r |4|
Closes #N/A
Related #N/A

Improve general user interface

---

tpl/config-debug.html.twig

We aren't using the bug collector tool so let's remove the form from the UI
|:---|:---:|
|@DIOHz0r |1|
Related #N/A

Hide unused bug collector tool

---

_includes/header.html
_layouts/container2.html
_layouts/static-docs.html

Update site's style

---

install/upgrade/update_to_dev.php
tests/suite-unit/PluginFlyvemdmEntityConfig.php
tools/cli_install.php

Hi, @flyve-mdm/backend-development.
I changed the configuration of mosquitto service for the test and this plugin. With this change we can edit the parameters like host and port mqqt dinamically
|:---|:---:|
|@ingluife |4|
|@btry |2|
Closes #576

Set host MQTT environment

---

inc/agent.class.php

The agent list shows wrong MDM types, this PR fix it.
|:---|:---:|
|@DIOHz0r |1|

Fix description for mdm types

---

inc/task.class.php
tests/suite-unit/PluginFlyvemdmTask.php

Add some tests to PluginFlyvemdmTask. Initiated because I had a right issue and I thought this was a bug.
tests on rights and prepareInputForAdd. Needs new tests for prepareInputForUpdate.
|:---|:---:|
|@btry |8|
Closes #N/A
Related #N/A

Add tests for tasks

---

tests/before_script.sh
tests/src/Flyvemdm/Tests/CommonTestCase.php
tests/src/Glpi/Tests/CommonTestCase.php
tests/suite-integration/PluginFlyvemdmAgent.php
tests/suite-integration/PluginFlyvemdmFleet.php
tests/suite-unit/PluginFlyvemdmAgent.php

I found a bug for testing which was mixing the session of glpi user and guest user for enrol agents. this refactor fix that.
|:---|:---:|
|@diohz0r |8|
Related #601

Refactor code for keep or change session on tests

---

_sass/_index.scss

Update responsive web design

---

tests/suite-integration/PluginFlyvemdmAgent.php
tests/suite-integration/PluginFlyvemdmTask.php
tests/suite-unit/PluginFlyvemdmAgent.php
tests/suite-unit/PluginFlyvemdmFusionInventory.php
tests/suite-unit/PluginFlyvemdmInvitation.php

Added new tests for the agent class
|:---|:---:|
|@diohz0r |99|

New unit tests for Agents

---

_sass/_general.scss
_sass/_index.scss

Adjust text of the Index and of the Development/M2M Specifications to adaptate to responsive web design.

Adaptate to responsive web design

---

setup.php

Update the plugin setup script which missed to include the autoloader on some status
|:---|:---:|
|@DIOHz0r |4|
Closes #616

Fix for plugin upgrade

---

.travis.yml
CHANGELOG.md
RoboFile.php
composer.json
package.json
plugin.xml
setup.php

Update various files to have a good build process
|:---|:---:|
|@btry |6|
Closes #N/A
Related #N/A

Build workflow update

---

tests/after_success.sh

Update script code to publish documentation on gh-pages if some CI changes happen
|:---|:---:|
|@DIOHz0r |2|
Related #N/A

Script update for publishing changes to gh-pages

---

tests/after_success.sh

This change allows CI to remove pages for documentation when a report file is deleted 
|:---|:---:|
|@DIOHz0r |2|
Closes #N/A
Related #N/A

Delete removed reports on CI

---

tests/after_success.sh

This is a quick patch for PR #627 
|:---|:---:|
|@DIOHz0r |1|
Related #N/A

Patch for deletion of old coverage report

---

RoboFile.php
composer.json
composer.lock

Enhance the build of an archive with packages.
Warning: the PR contans commits related to rhe RC1 release. do NOT merge before the release is published !
|:---|:---:|
|@btry |3|
Closes #N/A
Related #N/A

Create archive with dependencies (vendor/ folder)

---

setup.php

Bump version to next pre-release, disable official release flag
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A

Bump version to 2.0.0-rc.2

---

tests/src/Flyvemdm/Tests/ApiRestTestCase.php
tests/src/Flyvemdm/Tests/CommonTestCase.php
tests/src/Glpi/Tests/ApiRestTestCase.php
tests/src/Glpi/Tests/CommonDBTestCase.php
tests/src/Glpi/Tests/CommonTestCase.php
tests/suite-integration/PluginFlyvemdmAgent.php
tests/suite-integration/PluginFlyvemdmFile.php
tests/suite-integration/PluginFlyvemdmFleet.php
tests/suite-integration/PluginFlyvemdmPackage.php
tests/suite-integration/PluginFlyvemdmPolicyDeployFile.php
tests/suite-integration/PluginFlyvemdmPolicyRemoveFile.php
tests/suite-integration/PluginFlyvemdmTask.php
tests/suite-unit/PluginFlyvemdmFleet.php
tests/suite-unit/PluginFlyvemdmFusionInventory.php
tests/suite-unit/PluginFlyvemdmPackage.php
tests/suite-unit/PluginFlyvemdmPolicyDropdown.php
tests/suite-unit/PluginFlyvemdmTask.php
tpl/agent_fleet.html.twig
tpl/agent_taskstatus.html.twig

This is a minor code update including refactoring and PHPDoc blocks update .
|:---|:---:|
|@DIOHz0r |8|
Related #N/A

Update code for tests and templates

---

tests/suite-unit/PluginFlyvemdmPolicyBase.php

Added a missing unit test for PolicyBase class
|:---|:---:|
|@DIOHz0r |2|
Related #N/A

Add formGenerator test

---

.eslintignore
_includes/header.html
_layouts/code-documentation.html
_layouts/container2.html
_layouts/post.html
_layouts/static-docs.html
_sass/_general.scss
_sass/_index.scss

Improve the Responsive web design of the Index (sass/_index.scss).

Responsive web design

---

tests/suite-unit/PluginFlyvemdmTask.php

Added new unit tests and some refactor for the Task class
|:---|:---:|
|@DIOHz0r |17|
Related #N/A

New tests for Taks class

---

.travis.yml
install/installer.class.php
tests/before_script.sh
tests/plugin_flyvemdm_config_2.0.0-rc.1.sql
tests/plugin_flyvemdm_empty_2.0.0-rc.1.sql
tests/src/Glpi/Tests/CommonDBTestCase.php
tests/suite-install/Config.php

Introduce tests for upgrade of the plugin
Note that the code provided by GLPI to get the CREATE TABLE statements removes the specification of the DB engine. Therefore the comparison in the unit tests excludes the engine.
|:---|:---:|
|@btry |8|
Closes #N/A
Related #N/A

Upgrade tests

---

tests/suite-unit/PluginFlyvemdmTask.php

Added new unit tests for Taks updates
|:---|:---:|
|@DIOHz0r |13|
Related #N/A

Add unit test for Tasks

---

.travis.yml
tests/suite-unit/PluginFlyvemdmPolicyBase.php
tests/suite-unit/PluginFlyvemdmPolicyDeployapplication.php
tests/suite-unit/PluginFlyvemdmPolicyDeployfile.php

On gh-pages branch, the report doesn't show the index page, the generated files are showing less coverage that really are tested and also some links are lost. This is a know issue and reported on atoum project. 
The idea is to fix this temporally generating the report based on unit tests results.
|:---|:---:|
|@DIOHz0r |11|
Related #N/A

Unit tests after integration tests

---

.travis.yml
inc/entityconfig.class.php
inc/graph.class.php
inc/policydeployapplication.class.php
tests/suite-install/Config.php
tests/suite-integration/PluginFlyvemdmAgent.php
tests/suite-unit/PluginFlyvemdmEntityConfig.php

Fusion Inventory may have issues in its installation which may break our tests. This PR uses the CLI installer of Fusion Inventory to prevent impact on our tests.
installatin of Fusion Ivnentory done in .travis.yml
|:---|:---:|
|@btry  |3|
Closes #N/A
Related #N/A

Move FusionInventory install out ot tests

---

tests/suite-install/Config.php

To ensure that updating .travis.yml does not break tests in a nasty way
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A

Test avoid duplicate string

---

inc/agent.class.php
inc/entityconfig.class.php
inc/file.class.php
inc/fleet.class.php
inc/geolocation.class.php
inc/invitation.class.php
inc/invitationlog.class.php
inc/package.class.php
inc/policy.class.php
inc/policycategory.class.php
inc/task.class.php
inc/taskstatus.class.php
inc/wellknownpath.class.php

While working on an other plugin, I created equivalent patch.
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A

Compatibiliy with GLPI 9.4

---

composer.json

typo, and bad key
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A

Errors in composer

---

RoboFile.php
hook.php
install/install.class.php
install/installer.class.php
tests/suite-install/Config.php
tests/suite-uninstall/Config.php

Introduce a schema version of the database for the plugin, which should match the 2 major numbers of the version of the plugin. The schema shall not change for bugfixes.
Also, the release rc.1 still has the update_to_dev migration script, this was a miss. 
TODO:
add a check in Robo file to detect this file, or each time we reelase, bump version for the development branch and make upgrade_to_xx script . To be refined...
|:---|:---:|
|@btry |3|
Closes #N/A
Related #N/A

Fix upgrade

---

tests/src/Flyvemdm/Tests/CommonTestCase.php

This PR allows the creation of data needed for some tests. 
|:---|:---:|
|@DIOHz0r |9|
Related #N/A

Task and Taskstatus data for tests

---

_layouts/default.html
_sass/_general.scss
_sass/_index.scss

Signed-off-by: Esteban Matheus <ematheus@teclib.com>
Continue to update the style of the project site following the UWP guidelines as stated in PR #501, PR
#546, PR #556, PR #581, PR #591, PR #603, PR #606, PR #619, PR #624 and PR #657.
* Recreate the style found in Fluent Design apps.
* Fix linter warnings in the scss files:
* Follow the sass style guide to resolve the linter warnings. 
|:---|:---:|
|@E1matheus |3|
Closes #N/A
Related #626

Fix linter warnings

---

tpl/config-wizard.html.twig

Fix typo in wizard instructions
|:---|:---:|
|@Naylin15 |1|
Closes #N/A
Related #N/A

Fix typo DBMD to DBMS

---

.atoum.php
tests/after_success.sh

This PR is to set the reports according with the new structure for the site.
|:---|:---:|
|@DIOHz0r |4|
Related #678 
Depends on #682

Change for coverage report

---

inc/package.class.php

when running pasrPackage manually, we have a warning about package not uploaded. This is normal. Let's avoid the message.
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A

Warnings when running manually parsePackage

---

inc/policy.class.php

fix policy categories wihout items in task creation.
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A

Dropdown shall not show empty categories

---

install/policies/mdm.php
tests/src/Flyvemdm/Tests/CommonTestCase.php

create a new policy to allow or disallow test of policies.
This solves risks of unwanted policy settings by users.
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A 

Protect policies test with a policy

---

tests/after_success.sh

The shell script to update the code coverage is failing because a wrong conditional sentence, this will fix the issue
|:---|:---:|
|@DIOHz0r |8|
Related #678

Hot fix for generate code coverge

---

hook.php
inc/agent.class.php
inc/geolocation.class.php
tests/suite-unit/PluginFlyvemdmAgent.php

|:---|:---:|
|@btry |2|
Closes #710 
Related #N/A

Fix sql err

---

.travis.yml
tests/after_success.sh
tests/apidocs.sh

This PR update the CI scripts for create code documentation
|:---|:---:|
|@DIOHz0r |8|
Closes #694

Script for publishing code documentation

---

tests/suite-install/Config.php
tests/suite-integration/Entity.php
tests/suite-integration/PluginFlyvemdmAgent.php
tests/suite-integration/PluginFlyvemdmMqttuser.php
tests/suite-integration/ProfileRight.php
tests/suite-uninstall/Config.php
tests/suite-unit/PluginFlyvemdmAgent.php
tests/suite-unit/PluginFlyvemdmCommon.php
tests/suite-unit/PluginFlyvemdmEntityConfig.php
tests/suite-unit/PluginFlyvemdmFleet.php
tests/suite-unit/PluginFlyvemdmFusionInventory.php
tests/suite-unit/PluginFlyvemdmPolicyBoolean.php
tests/suite-unit/PluginFlyvemdmPolicyDeployapplication.php
tests/suite-unit/PluginFlyvemdmPolicyDeployfile.php
tests/suite-unit/PluginFlyvemdmPolicyDropdown.php
tests/suite-unit/PluginFlyvemdmPolicyInteger.php
tests/suite-unit/PluginFlyvemdmPolicyRemoveapplication.php
tests/suite-unit/PluginFlyvemdmPolicyString.php
tests/suite-unit/PluginFlyvemdmTask.php

Small refactor of code for tests.
|:---|:---:|
|@DIOHZ0r |9|
Closes #N/A
Related #N/A

Tests refactor

---

inc/agent.class.php
inc/entityconfig.class.php
inc/file.class.php
inc/fleet.class.php
inc/geolocation.class.php
inc/invitation.class.php
inc/invitationlog.class.php
inc/package.class.php
inc/policy.class.php
inc/policycategory.class.php
inc/task.class.php
inc/taskstatus.class.php
inc/wellknownpath.class.php

it seems we need this to allow GLPI 9.3 to correctly customize display prefs
|:---|:---:|
|@btry |2|
Closes #N/A
Related #N/A

backport compatibility with GLPI 9.4

---

.atoum.php
.travis.yml
composer.json
composer.lock
tests/after_success.sh
tests/apidocs.sh

I've noticed that after generated RC2 the documentation for master wasn't updated because the script change was not on the release branch. This must fix the issue
|:---|:---:|
|@DIOHz0r |2|
Closes #N/A
Related #N/A

Add CI script for documentation

---

inc/package.class.php

see implementation of prepareInputForAdd
Signed-off-by: Thierry Bugier <tbugier@teclib.com>
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A

Wrong dl_filename when updating a package

---

setup.php

development branch bump !
|:---|:---:|
|@ |1|
Closes #N/A
Related #N/A

Bump to development version

---

inc/package.class.php

|:---|:---:|
|@btry |3|
Closes #N/A
Related #N/A

Fix dl filename

---

setup.php

develop branch is not an official release ;)
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A

Demote official bit

---

install/install.class.php
tools/cli_install.php

Try to disable time limit for upgrades from GLPI user interface. 
|:---|:---:|
|@btry |1|
Closes #729
Related #N/A

fix(install):time limit when upgrading from glpi

---

scripts/flyvemdm.service

Add a systemd service definition for the daemon
Credits go to @spinaldf
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A

SystemD service

---

inc/agent.class.php
inc/fleet.class.php
inc/mqttlog.class.php
inc/profile.class.php
install/install.class.php
install/upgrade_to_2.0.php
tests/suite-integration/ProfileRight.php
tests/suite-unit/PluginFlyvemdmMqttlog.php
tpl/mqttlog_list.html.twig

New tabs for fleets and agents
Profile rights for logs
|:---|:---:|
|@DIOHz0r |31|
Closes #752

Add MQTT log tabs

---

inc/deployable.class.php
inc/package.class.php
tests/src/Flyvemdm/Tests/CommonTestCase.php
tests/suite-unit/PluginFlyvemdmPackage.php

|:---|:---:|
|@DIOHz0r |22|
Closes #748

Disable MQTT messages on wrong app filename

---

inc/package.class.php
tests/suite-unit/PluginFlyvemdmPackage.php

make the methos the same accross develop and release branches
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A

refactor(package): prevent a php warning

---

RoboFile.php
locales/ca_ES.po
locales/cs_CZ.po
locales/es_AR.po
locales/es_ES.po
locales/es_MX.po
locales/flyvemdm.pot
locales/fr_FR.po
locales/pt_BR.po

This change update the locales files for the release, the Spanish versions is also translated at 100%
|:---|:---:|
|@DIOHz0r |15|
Related #N/A

Locales update for release

---

inc/agent.class.php
inc/invitation.class.php
tests/before_script.sh
tests/src/Flyvemdm/Tests/CommonTestCase.php
tests/suite-integration/Entity.php
tests/suite-integration/PluginFlyvemdmAgent.php
tests/suite-integration/PluginFlyvemdmInvitation.php
tests/suite-unit/PluginFlyvemdmInvitation.php
tpl/invitation.html.twig

instead of giving en email to create an invitation, we give a user. This solves the issue mentioned below.
|:---|:---:|
|@btry |10|
Closes #769 
Related #N/A
Depends on #https://github.com/flyve-mdm/web-mdm-dashboard/issues/1135

Invitation rework

---

inc/agent.class.php
inc/mqtthandler.class.php
inc/mqttlog.class.php
tests/suite-integration/PluginFlyvemdmAgent.php
tpl/agent.html.twig

There is a mismatch between the offline message sent by the agent and the expected format in the backend
the agent sends a boolean while the plugin expects strings 'true' or 'false'. Switching to boolean.
For debug purposes, I enhanced the UI of the agent to show the online status.
|:---|:---:|
|@btry  |2|
Closes #N/A
Related #N/A

Fix offline event handling

---

inc/invitation.class.php
install/install.class.php

GLPI resize the attached file if the image is less than 400px x 300px and convert it to JPEG format, this PR fixes the issue.
|:---|:---:|
|@DIOHz0r |6|
Closes #781

Avoid QR code format change

---

setup.php
tests/bootstrap.php

compatibility of unit tests with GLPI 9.4
|:---|:---:|
|@btry  |2|
Closes #N/A
Related #N/A

Compatibility of unit tests with GLPI 9.4

---

inc/agent.class.php

Remove whitespace in ``Danger zone !``
|:---|:---:|
|@Naylin15 |1|
Closes #N/A
Related #N/A

Remove whitespace

---

inc/agent.class.php

remove new line in the historical tab of agent for online status rows

Improve status display

---

.travis.yml
inc/agent.class.php
inc/common.class.php
inc/geolocation.class.php
inc/mqtthandler.class.php
inc/profile.class.php
inc/taskstatus.class.php
install/install.class.php
tests/src/Flyvemdm/Tests/CommonTestCase.php
tests/suite-integration/ProfileRight.php
tests/suite-unit/PluginFlyvemdmAgent.php
tests/suite-unit/PluginFlyvemdmCommon.php
tests/suite-unit/PluginFlyvemdmGeolocation.php
tests/suite-unit/PluginFlyvemdmPackage.php
tests/suite-unit/PluginFlyvemdmTaskstatus.php

Change the device responses from MQTT to HTTP through GLPI API and its endpoints.
|:---|:---:|
|@DIOHz0r | 101 |
Closes #793

Handle device responses via HTTP

---

_includes/contact/social.html

Fix Twitter display
|:---|:---:|
|@Naylin15 |1|
Closes #N/A
Related #N/A

Fix twitter url

---

inc/agent.class.php
install/mysql/plugin_flyvemdm_empty.sql
install/upgrade_to_2_0.php
tests/src/Flyvemdm/Tests/CommonTestCase.php
tests/suite-integration/PluginFlyvemdmAgent.php
tests/suite-integration/PluginFlyvemdmFleet.php
tpl/_agentInfo.html.twig
tpl/agent.html.twig

|:---|:---:|
|@btry |2|
|@DIOHz0r |14|
Closes #N/A
Related #N/A

Notification token in enrollment for FCM

---

inc/agent.class.php

A cherry pick generated a conflict. I introduced an error while solving it. This PR should fix the bug.
|:---|:---:|
|@btry |1|
Closes #N/A
Related #N/A

Enrollment broken due to bad merge conflictr resolution

---

_includes/header.html
sw.js

Add DB scheme
fix coverage url
remove screenshots url
|:---|:---:|
|@Naylin15 |1|
Closes #812 
Related #N/A

Add DB scheme

---

inc/graph.class.php

Changed the graph types for better UX
|:---|:---:|
|@DIOHz0r |3|
Related #N/A

Change graph types for dashboard

---

tpl/config-wizard.html.twig

The links to message queue redirect to GLPI configuration and not the plugin's
|:---|:---:|
|@Naylin15 |2|
Closes #N/A
Related #N/A

Fix links in wizard
